### ISSUE TITLE
IE Beacon Issue

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#430] opened 2015-09-23 20:52 UTC
From SBRF, got reports that Beacon form is clearing information when the required field warning message flashes. Need to look into this, but unclear how to get around IE form weirdness

**Comment by bsmithgall** [comment] 2015-09-23 20:53
What do you mean "clearing information"

**Comment by hamhands** [comment] 2015-09-23 20:53
Meaning the forms are cleared.

**Comment by bsmithgall** [comment] 2015-09-23 20:54
Do you have a screenshot? Are you sure it's IE only? Is it all fields?

**Comment by bsmithgall** [comment] 2015-09-24 17:25
I tested this on browserstack and couldn't reproduce.

**Comment by hamhands** [comment] 2015-09-24 17:28
@bsmithgall I got the card of the guy who reported it if we want to pursue further

**Comment by hamhands** [comment] 2015-09-24 17:28
or wontfix?

**Comment by bsmithgall** [comment] 2015-09-24 18:30
Yeah, I'm not sure. I think we should just WONTFIX this -- I checked the browser usage stats and this guy was literally the _only person_ visiting on IE8

**Closed as completed** 2015-09-25 23:27 UTC
Labels: bug, wontfix, beacon
