### ISSUE TITLE
beaconbot url issues

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#336] opened 2015-09-03 18:24 UTC
Beaconbot isn't including the baseurl in the links:
<img width="1280" alt="screen shot 2015-09-03 at 11 23 55 am" src="https://cloud.githubusercontent.com/assets/3640800/9667037/58da8f6c-522e-11e5-8b52-79b5a5fe1b0e.png">

**Comment by bsmithgall** [comment] 2015-09-03 18:44
Duplicate of #326

**Closed as completed by bsmithgall** 2015-09-03 18:44 UTC
Labels: wontfix, meta
