### ISSUE TITLE
Beacon still throwing 500s with weird rquot characters

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#578] opened 2015-11-03 18:35 UTC

**Comment by bsmithgall** [comment] 2015-11-03 18:44
Not in the logs though.

**Comment by bsmithgall** [comment] 2015-11-03 19:38
@hamhands can you see if you can repro this?

**Comment by hamhands** [comment] 2015-11-03 19:56
@bsmithgall :+1:

**Comment by hamhands** [comment] 2015-11-03 22:29
Can't reproduce this error so it looks like this was in fact fixed in #525. Will email Jennifer.

**Closed as completed by hamhands** 2015-11-03 22:29 UTC
Labels: bug, beacon
