### ISSUE TITLE
Category flow for contracts is a bit confusing

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#282] opened 2015-08-25 16:33 UTC
From user testing notes from sessions w/Ed & Stephanie:

> I’m not totally sure that the category flow is really working for contracts in the same way that it does for the vendors. It seems like people only want to use only one category, so it seems like we’ll have a lot of opps that get created that don’t necessarily have people who are subscribed to that contract. There are also a lot of contracts that don’t have intuitive matches.

**Comment by bsmithgall** [comment] 2015-09-08 16:39
@shellicious @hamhands I feel like this is related to #285. I'm not totally sure what a better UI would be -- the thing I like about the current flow is that people are encouraged to sign up for things in bulk, while a search-type infrastructure using something like [chosen](https://harvesthq.github.io/chosen/) or [select2](http://select2.github.io/) might decrease the total number of categories folks are signing up for.

**Comment by msknee** [comment] 2015-10-29 19:14
Duplicate of #470

**Closed as completed by msknee** 2015-10-29 19:14 UTC
Labels: wontfix, conductor, beacon
