### ISSUE TITLE
We should migrate any contracts follows from Wexplorer to Scout

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#267] opened 2015-08-24 17:27 UTC

**Comment by msknee** [comment] 2015-09-15 00:10
Duplicate of #219?

**Comment by bsmithgall** [comment] 2015-09-15 00:11
No, this is from wexplorer itself, which I haven't pulled any data from I'm pretty sure.

**Closed as completed** 2015-10-29 19:12 UTC
Labels: scout, meta, launch requirement
