### ISSUE TITLE
Master IT Services ITQ PDF

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#557] opened 2015-10-28 17:47 UTC
Running through the state contracts and I can't find a single instance where [Master IT Services ITQ](https://www.buildpgh.com/scout/search?q=master+|+it+|+services&contract_type=12) actually returns a PDF when clicking "View contract".

![itq](https://cloud.githubusercontent.com/assets/3640800/10797725/2fcac1c4-7d61-11e5-88de-7f6d818c887f.gif)

We may need to construct the URL differently for these contracts or remove the link entirely.

**Comment by bsmithgall** [comment] 2015-10-28 17:50
We'll probably need to bulk update these -- good catch. Can you find the working link for the verizon one and we can figure out what the problem is?

**Comment by hamhands** [comment] 2015-10-28 17:56
@bsmithgall there isn't a unique contract file for each contract, but one overview file for all suppliers under the same parent number. The URLs are unique though. For example [here's the overview file for verizon](http://www.emarketplace.state.pa.us/FileDownload.aspx?file=4400008251Overview.pdf) and [here's the overview file for xerox](http://www.emarketplace.state.pa.us/FileDownload.aspx?file=4400006605Overview.pdf)

**Comment by bsmithgall** [comment] 2015-10-28 17:57
Is that always true for all state contracts?

**Comment by hamhands** [comment] 2015-10-28 17:57
No, just for the Master IT Services ITQ contracts as far as I can tell.

**Comment by hamhands** [comment] 2015-10-28 17:59
There's only [one other ITQ state contract](https://www.buildpgh.com/scout/contracts/2634) and the pdf works.

**Comment by bsmithgall** [comment] 2015-10-28 18:00
Ok. So the solution is to bulk-update the ITQ contract?

**Comment by bsmithgall** [comment] 2015-10-28 18:01
@hamhands it might be worthwhile to load in all of the state contracts into your localdb and poke around and see if anything else is broken

**Comment by bsmithgall** [comment] 2015-10-28 18:03
`http://www.emarketplace.state.pa.us/FileDownload.aspx?file=4400006605\Overview.pdf`

**Comment by hamhands** [comment] 2015-10-28 18:04
Man, markdown stripping out the `\` really bums me out

**Comment by hamhands** [comment] 2015-10-28 23:50
Finished QAing the contract_href for all the state contract types. Master IT Services ITQ (393 total contracts) is the only group where the url concat isn't correct.

Format: `http://www.emarketplace.state.pa.us/FileDownload.aspx?file={number}\Overview.pdf`

**Comment by bsmithgall** [comment] 2015-10-29 17:41
Script to update existing contracts:

``` python
import sqlalchemy as sa

from purchasing.data.contracts import ContractBase, ContractProperty
from purchasing.utils import turn_off_sqlalchemy_events, turn_on_sqlalchemy_events

itq_base = 'http://www.emarketplace.state.pa.us/FileDownload.aspx?file={number}\Overview.pdf'

contracts = ContractBase.query.filter(
    db.func.lower(ContractBase.description) == 'master it services itq',
    ContractBase.contract_type_id == 12,
).all()

for contract in contracts:
    try:
        turn_off_sqlalchemy_events()
    except sa.exc.InvalidRequestError:
        pass
    try:
        contract_number = [i for i in contract.properties if i.key.lower() == 'contract number'][0]
        contract.contract_href = itq_base.format(number=contract_number.value)
    except IndexError:
        pass

db.session.commit()
turn_on_sqlalchemy_events()
```

Will also push an update to the `import_state` method

**Comment by bsmithgall** [comment] 2015-10-29 17:47
This is fixed in prod, import fix incoming, then I'll close this issue.

**Comment by hamhands** [comment] 2015-10-29 18:05
sounds good @bsmithgall!

**Closed as completed** 2015-10-29 18:06 UTC
Labels: bug, scout
