### ISSUE TITLE
Beacon nav formatting issues for phone / tablet resolutions

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#322] opened 2015-09-01 22:21 UTC
Margins look funky. We should fix in the event that people at the press conference are on mobile, and to take a nice screencap for the slide. 

![screen shot 2015-09-01 at 3 20 08 pm](https://cloud.githubusercontent.com/assets/1178390/9618650/163e4e2c-50bd-11e5-977c-6b3538797350.png)

![screen shot 2015-09-01 at 3 20 52 pm](https://cloud.githubusercontent.com/assets/1178390/9618649/163d60a2-50bd-11e5-878d-8e4575e03b34.png)

**Comment by bsmithgall** [comment] 2015-09-01 22:28
Duplicate of #233 I think

**Closed as completed** 2015-09-03 18:46 UTC
Labels: beacon, launch requirement
