### ISSUE TITLE
Atlas-fy

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#197] opened 2015-08-11 00:02 UTC
The remnants of Sherpa still _lurk_ within the suite. We must resolve this discrepancy lest we lead users astray in an ironic fashion.

**Comment by bsmithgall** [comment] 2015-08-11 00:03
This is a partial duplicate of #52

**Comment by msknee** [comment] 2015-08-12 23:24
I spy it in:
- [x] index page of The Suite
- [x] Apps dropdown
- [x] Navbar of Atlas

**Closed as completed** 2015-08-13 00:25 UTC
Labels: atlas
