### ISSUE TITLE
can't change contract description

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#609] opened 2015-11-19 15:26 UTC
Description won't change for contracts via admin::Scout::Contracts

I'm trying to change the description for every single 4400004480 state contract.  I change it and hit submit and it won't change.  i've also tried hitting save and continue and it doesn't save.

**Comment by bsmithgall** [comment] 2015-11-19 17:16
What are you trying to change it to, and from what?

**Comment by bsmithgall** [comment] 2015-11-19 17:25
I tried based based on a pattern that you provided and had no trouble. 

There are 393 of these; do you want me to bulk-update them in one go?

**Comment by rileystewart** [comment] 2015-11-19 18:15
it's still not working for me.

i am trying to change them to MASTER IT SERVICES ITQ- CONTACT PROCUREMENT
BEFORE USING https://www.buildpgh.com/admin/contract/?search=4400004480#

I just tried with Collective Intelligence and it doesn't change

**Comment by bsmithgall** [comment] 2015-11-19 18:21
It updated for me just fine: https://www.buildpgh.com/admin/contract/?search=collective+intelligence

Are you using the individual page edit or editing by clicking on the description and changing it that way?

**Comment by rileystewart** [comment] 2015-11-19 19:09
i'm on Admin::Scout::Contracts and searched the contract number.  I got all
of page one done but it won't update/save any on page 2.

**Comment by bsmithgall** [comment] 2015-11-19 19:36
I can't reproduce this issue locally or in production, so I am not really sure what to do here. Riley if you want to just add that contact procurement before using, I can do that in bulk at the database level so you don't have to do 330 times.

**Comment by rileystewart** [comment] 2015-11-19 19:40
ya I'd like that for this case. i found out that state contract is more
just like a PQ so i want to make sure we tell ppl to contact us so we can
explain before they buy with the vendor

**Comment by bsmithgall** [comment] 2015-11-19 19:43
Ok, I will do that and then close this issue

**Closed as completed** 2015-11-19 19:48 UTC
Labels: admin
